### PR TITLE
Create EightSumsUp.py

### PR DESCRIPTION
**Pull request by Jayshah6699**
## Description

Write here what you have changed

**Issue No.**- #31 
> Type issue number after hash(#)

## Checklist

- [x] Yes, this task assigned to me.
- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My Filename is in camelCase format
- [x] I have added **Problem statement**, **Problem link** in file.

### CODE REVIEW

**Comment by Jayshah6699** [comment]
@aayushi-droid check

**Comment by aayushi-droid** [comment]
what I will check there is no issue number

**Comment by Jayshah6699** [comment]
@aayushi-droid issue no #31 check

**Comment by Jayshah6699** [comment]
@aayushi-droid kindly merge the pull request

**Comment by Jayshah6699** [comment]
@aayushi-droid as per the new rules kindly merge all the pullrequests and add the hacktoberfest-completed label too as soon as possible as my pullrequest is going to mature in 8 days thank you and now I have added the issue numbers to all of my pull requests
Thank you

**Pull request merged**
