### PR TITLE
Solution to oddish evenish number problem

### PR DESCRIPTION
**Pull request by asiskumarroy**
## Description

Write here what you have changed

**Issue No.**- #195 
> Type issue number after hash(#)

## Checklist

- [ ] Yes, this task assigned to me.
- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My Filename is in camelCase format
- [x] I have added **Problem statement**, **Problem link** in file.

### CODE REVIEW

**Comment by aayushi-droid** [comment]
Invalid PR

**Comment by asiskumarroy** [comment]
hello i did not change but added a new PR
can you please state why is this PR invalid so that
i can make necessary changes

**Comment by asiskumarroy** [comment]
I am new to github so i might have commited some mistake.I would be glad if you help me out in the process to grow

**Comment by aayushi-droid** [comment]
Unassigned Pr, please go through documentation.

**Pull request closed without merging**
