### PR TITLE
Create ConnectingWords.py

### PR DESCRIPTION
**Pull request by Jayshah6699**
## Description

Write here what you have changed

**Issue No.**- #30 
> Type issue number after hash(#)

## Checklist

- [x] Yes, this task assigned to me.
- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My Filename is in camelCase format
- [x] I have added **Problem statement**, **Problem link** in file.

### CODE REVIEW

**Comment by Jayshah6699** [comment]
@aayushi-droid check

**Comment by aayushi-droid** [comment]
Issue no. is not found

**Comment by Jayshah6699** [comment]
@aayushi-droid issue no #30 check

**Comment by Jayshah6699** [comment]
@aayushi-droid kindly merge the pull request

**Comment by Jayshah6699** [comment]
@aayushi-droid kindly do the needful

**Comment by Jayshah6699** [comment]
@aayushi-droid kindly add hacktoberfest-completed tag and merge the pull request

**Pull request merged**
